@startuml
title ELIMINAZIONE LIBRO

actor Bibliotecario
participant View
participant Controller 
participant BookManagement
participant FileManager

Bibliotecario -> View : Inserisce dati libro da eliminare
Bibliotecario -> View : Conferma
ref over Controller,BookManagement
Search
end
Bibliotecario -> View : Elimina
View -> Controller : Invia dati da eliminare
Controller -> BookManagement : remove(Book b)
BookManagement -> FileManager : updateFileObject(Catalogue,bookDatabase)
BookManagement --> Controller : returnValue
alt [Errore_nella_rimozione]
Controller -> View : ErrorView("Rimozione non avvenuta")
else [Rimozione_avvenuta]
Controller -> View : removeSuccess("Eliminazione avvenuta con successo")
end
@enduml

