@startuml

interface Serializable
interface Comparable

class Application 

class View {
  + start(stage: Stage): void
  + main(args: String[]): void {static}
}

class Controller {
  - model : Model
  - view : View
  + Controller(model : Model, view : View) : View
  + initBindings() : void
  + initHandler() : void
}

class Model {
  - BookManagement bookManagement
  - LoanManagement loanManagement
  - UserManagement userManagement
  - Librarian librarian
  + Model(bookManagement: BookManagement, userManagement: UserManagement, loanManagement: LoanManagement, librarian: Librarian)
  + getBookManagement(): BookManagement
  + setBookManagement(BookManagement): void
  + getUserManagement(): UserManagement
  + setUserManagement(UserManagement): void
  + getLoanManagement(): LoanManagement
  + setLoanManagement(LoanManagement): void
  + getLibrarian(): Librarian
  + setLibrarian(Librarian): void
}

class Librarian {
  - username: String
  - password: String
  - filepath: String = "credentials.txt"
  + getUsername() : String
  + getPassword() : String
  + checkCredentials(usernameInput : String, passwordInput : String)
  + modifyCredentials(newUsername : String, newPassword : String)
}

class User {
  - name : String
  - surname : String
  - numberId : String
  - email : String
  - booksOnLoan : Map<Book, LocalDate>
  + User(name: String, surname: String, numberId: String, email: String)
  + setName(name: String): void
  + setSurname(surname: String): void
  + setEmail(email: String): void
  + setBooksOnLoan(newMap: TreeMap<Book, LocalDate>): void
  + getName(): String
  + getSurname(): String
  + getNumberId(): String
  + getEmail(): String
  + getBooksOnLoan(): Map<Book, LocalDate>
  + compareTo(other: User): int
  + findLoans(l: LoanManagement, s: String): Map<Book, LocalDate>
}

class Book {
  - title : String
  - authors : String
  - publicationYear : LocalDate
  - ISBN : String
  - availableCopies : int
  +Book(title: String, authors: String, publicationYear: LocalDate, ISBN: String, availableCopies: int)
  + getTitle() : String
  + getAuthors() : String
  + getPublicationYear() : LocalDate
  + getISBN() : String
  + getAvailableCopies() : int
  + setTitle(title : String) : void
  + setAuthors(authors : String) : void
  + setPublicationYear(publicationYear : LocalDate) : void
  + setISBN(ISBN : String) : void
  + setAvailableCopies(availableCopies : int) : void
  +compareTo(other : Book) : int
}

class Loan {
  - book: Book
  - user: User
  - dueDate: LocalDate
  + Loan(book: Book, user: User, dueDate: LocalDate)
  + getBook(): Book
  + getUser(): User
  + getDueDate(): LocalDate
  + setBook(book: Book): void
  + setUser(user: User): void
  + setDueDate(dueDate: LocalDate): void
  + compareTo(other: Loan): int
}

interface Functionality<T> {
  + add(entity: T): boolean
  + remove(entity: T): boolean
  + update(entity: T): boolean
  + viewSorted(): void
  + search(entity: T): T
}

class BookManagement {
  - catalogue: Set<Book>
  + BookManagement()
  + add(b: Book): boolean
  + remove(b: Book): boolean
  + update(b: Book): boolean
  + viewSorted(): void
  + search(b: Book): Book
}

class LoanManagement {
  - loans : Set<Loan>
  + LoanManagement()
  + add(l: Loan): boolean
  + remove(l: Loan): boolean
  + update(l: Loan): boolean
  + viewSorted(): void
  + search(l: Loan): Loan
}

class UserManagement {
  - list : Set<User> 
  + UserManagement()
  + add(u: User): void
  + remove(u: User): void
  + update(u: User): void
  + viewSorted(): void
  + search(s: String): User
}

class FileManager<T> {
  + removeFromTextFileObject(object: T, filename: String): void {static}
  + writeToTextFileObject(object: T, filename: String): void {static}
  + updateFileObject(newObject: T, filename: String): void{static}
  + readLine(filename: String): void{static}
  + writeLine(line: String, filename: String): void{static}
  + updateLine(line: String, filename: String): void{static}
}

Controller --> Model
Controller --> View
View --|> Application

Model --> BookManagement
Model --> LoanManagement
Model --> UserManagement
Model --> Librarian

User --> Book
User --> LoanManagement
User ..|> Comparable

Book ..|> Comparable


Loan --> Book
Loan --> User
Loan ..|> Comparable


BookManagement ..|> Functionality
BookManagement ..|> Serializable
BookManagement ..> Book

LoanManagement ..|> Functionality
LoanManagement ..|> Serializable
LoanManagement ..> Loan

UserManagement ..|> Functionality
UserManagement ..|> Serializable
UserManagement ..> User

FileManager ..|> Serializable

@enduml
