@startuml
title ELIMINAZIONE UTENTE

actor Bibliotecario
participant View
participant Controller 
participant UserManagement
participant User
participant  FileManager

Bibliotecario -> View: Accede al menù utente
View –-> Bibliotecario: Mostra opzioni disponibili
Bibliotecario -> View: Seleziona "Elimina Utente" 
View –-> Bibliotecario: Richiesta inserimento matricola
Bibliotecario –> View: Inserisce matricola
 View -> Controller : rimozione utente
Controller -> UserManagement: remove(User u )
 
UserManagement -> UserManagement : search(Useru)
UserManagement --> UserManagement: esito
 alt Utente NON esistente
	UserManagement --> Controller: UtenteNonTrovato
                Controller->View: errore:utente non trovato

	View --> Bibliotecario: Mostra errore
 
else Utente esistente
	UserManagement -> UserManagement: remove(User u)
	UserManagement --> UserManagement: confermaRimozione
	UserManagement --> Controller: confermaEliminazione
               Controller -->View: conferma eliminazione utente 
	View --> Bibliotecario: Utente eliminato con successo
 
	UserManagement -> FileManager: updateFileObject(listaUser, userDatabase);
 
end
@enduml
