@startuml
title INSERIMENTO LIBRO

actor Bibliotecario
participant View
participant Controller 
participant BookManagement
participant FileManager

Bibliotecario -> View : Inserisce dati del libro
Bibliotecario -> View : Conferma
View -> Controller : Invia dati Libro
Controller -> BookManagement : add(Book b)
BookManagement -> FileManager : writeToTextFileObject(Catologue,bookDatabase) 
BookManagement --> Controller : returnValue
alt [ Libro non inserito]
Controller -> View : ErrorView("Errore nell'Inserimento")
else [ Libro inserito correttamente]
Controller -> View : addSuccess("Libro Inserito")
end
@enduml


