@startuml
title MODIFICA DATI LIBRO

actor Bibliotecario
participant View
participant Controller 
participant BookManagement
participant FileManager

Bibliotecario -> View: Inserisci dati libro
Bibliotecario -> View: Conferma

ref over Controller, BookManagement
  Search
end ref

ref over View,Controller,BookManagement
 ViewOrdered
end

Bibliotecario -> View : Inserisci dati da modificare
Bibliotecario -> View : Conferma

View -> Controller : Invia dati da modificare
Controller -> BookManagement : update(Book b)

BookManagement -> FileManager: updateFileObject(Book B,String Filename)
BookManagement --> Controller: returnValue

alt [ Errore nella modifica]
  Controller -> View: ErrorView("I dati non sono stati aggiornati correttamente")

else [ Modifica avvenuta con successo]
  Controller -> View: updateSuccess("I dati sono stati aggiornati")
end

@enduml

