@startuml
skinparam packageStyle rectangle
left to right direction


package "src"{  
    package "model" {
        package "data" {
            class Book
            class User
            class Loan
        }

        package "management" {
            interface Functionality
            class BookManagement
            class UserManagement
            class LoanManagement
        }

        package "auth" {
            class Librarian
        }

        package "storage" {
            class FileManager
        }

        class Model
}

    package "view" {
        class View
    }

    package "control" {
        class LoginController
        class addBookController
        class addLoanController
        class addUsaerController
        class deleteBookController
        class deleteLoanController
        class deleteUserController
        class homepageController
        class loanViewController
        class modifyBookController
        class modifyUserController
        class modifycredentialController
        class searchBookController
        class searchLoanController
        class searchUserController
        class viewBookController
        class viewUserController
    }
  
' Relazioni MVC
view ..> control
control ..> model

' Relazioni interne al package model
management ..> data
management ..> storage
auth ..> data
auth ..> storage
auth ..> management
@enduml