@startuml
title RICERCA UTENTE

actor Bibliotecario
participant View
participant Controller 
participant UserManagement
participant User
 
Bibliotecario -> View: Accede al menù utente
View –> Bibliotecario: Mostra opzioni disponibili
Bibliotecario -> View: Seleziona "Ricerca Utente"
View –> Bibliotecario: Richiesta inserimento matricola/cognome
Bibliotecario -> View: Inserisce criteri di ricerca
 
View -> Controller: Ricerca utente
Controller -> UserManagement:  search(User u)
alt Utente non esistente
	UserManagement --> Controller: Errore: Utente non trovato
                Controller ->View: Notifica errore
	View --> Bibliotecario: Notifica errore
else Utente trovato
 	UserManagement->Controller:utente cercato
                  Controller ->View: utente cercato
 	View--> Bibliotecario: Visualizza dati utente
end
@enduml


