@startuml
title RICERCA LIBRO

actor Bibliotecario
participant View
participant Controller 
participant BookManagement

Bibliotecario -> View : Inserisce dati del libro da cercare
Bibliotecario -> View : Conferma
View -> Controller : Invia dati Libro
Controller -> BookManagement : search(Book b)
BookManagement --> Controller : returnBook
alt [ Libro non trovato]
Controller -> View : ErrorView("Errore nella ricerca")
else [ Libro trovato correttamente]
Controller -> View : Book
end
@enduml

