var _loan_management_8java =
[
    [ "it.unisa.diem.oop.gruppo14bibliotecauniversitaria.model.management.LoanManagement", "classit_1_1unisa_1_1diem_1_1oop_1_1gruppo14bibliotecauniversitaria_1_1model_1_1management_1_1_loan_management.html", "classit_1_1unisa_1_1diem_1_1oop_1_1gruppo14bibliotecauniversitaria_1_1model_1_1management_1_1_loan_management" ]
];